rough implementation of table_skel
enderesting/sd-projeto-2 pull request #5
Opened 2023-10-25 14:11 UTC by enderesting

- this is for `table_skel.c`, sorry for naming the branch wrong
- look up "CHECKTHIS" to look at all the stuff i didn't fully implemented in. sorry, i was running on time
- DO NOT merge until we figured it out it's good
- the first functions seem too easy to implement... i'm probably missing something?

2023-10-25 18:57 UTC, padrezulmiro requested changes
Please review notes

2023-10-25 18:57 UTC, padrezulmiro commented on source/table_skel.c
> +        case MESSAGE_T__OPCODE__OP_BAD:
Unfortunately, you have to wrap the code for the case in curly braces
```suggestion
        case MESSAGE_T__OPCODE__OP_BAD: {
            // Code here
        }
```

2023-10-25 18:57 UTC, padrezulmiro commented on source/table_skel.c
> +        case MESSAGE_T__OPCODE__OP_BAD:
![image](https://github.com/enderesting/sd-projeto-2/assets/1679672/c0007d18-efc7-4327-bc49-00b25964deeb)

2023-10-25 18:57 UTC, padrezulmiro commented on source/table_skel.c
> +    return table_create(n_lists);
Please add null check

2023-10-25 18:57 UTC, padrezulmiro commented on source/table_skel.c
> +            struct data_t *value = data_create(entry_size, msg->entry->value.data); // CHECKTHIS: is this the correct way of doing it
I don't think you want to use entry_size, especially not if entry_size is the packed size. What you should be using is msg->entry->value.[len](https://protobuf-c.github.io/protobuf-c/structProtobufCBinaryData.html#a32722312668d3d164765009c2c848777), IIRC

2023-10-25 18:57 UTC, padrezulmiro commented on source/table_skel.c
> +                msg->c_type = MESSAGE_T__C_TYPE__CT_NONE;
I'm not sure if this message that's being reused (according to the docs) is the same one that'll be packed and sent to the client. But if it is, then I think you should empty the fields that were being used before, eg the entry field.

2023-10-25 18:57 UTC, padrezulmiro commented on source/table_skel.c
> +                msg->c_type = MESSAGE_T__C_TYPE__CT_NONE;
If table_put fails (== -1) then the message needs to be filled up with OP_ERROR and CT_NONE

2023-10-25 18:57 UTC, padrezulmiro commented on source/table_skel.c
> +                printf("Error in rtable_get or key not found!\n");
Here, msg needs to be filled up with OP_ERROR etc

2023-10-25 18:57 UTC, padrezulmiro commented on source/table_skel.c
> +            //CHECKTHIS: how to handle error?
I don't think that there's anything to do, in principle this should never happen, since client doesn't send commands with OP_ERROR

2023-10-25 18:57 UTC, padrezulmiro commented on source/table_skel.c
> +int invoke(MessageT *msg, struct table_t *table){
According to the project notes the returned OP_CODE for each of the operations should be OP_CODE+1, if successful. 
![image](https://github.com/enderesting/sd-projeto-2/assets/1679672/c7748823-6b6e-4e53-a56b-3851ec335975)

2023-10-25 19:17 UTC, enderesting commented on source/table_skel.c
> +        case MESSAGE_T__OPCODE__OP_BAD:
oh weird, i don't remember switch case needing curly brackets...

2023-10-25 19:19 UTC, enderesting commented on source/table_skel.c
> +    return table_create(n_lists);
these are all included in `table_create` already! can't think of any other cases it could become null besides inside that function

2023-10-25 19:19 UTC, enderesting commented on source/table_skel.c
> +        case MESSAGE_T__OPCODE__OP_BAD:
nvm, if u declare variables in it it does need them

2023-10-25 19:20 UTC, enderesting commented on source/table_skel.c
> +            struct data_t *value = data_create(entry_size, msg->entry->value.data); // CHECKTHIS: is this the correct way of doing it
yep, fixed. this was before our clarifications and i forgot to update XP

2023-10-25 19:24 UTC, enderesting commented on source/table_skel.c
> +                msg->c_type = MESSAGE_T__C_TYPE__CT_NONE;
Both this and the correct opcode are all accounted for at the end, after you exit the switch case XD I guess it wasn't very clear, so I'm going to tidy it up a bit more

2023-10-25 19:33 UTC, enderesting commented on source/table_skel.c
> +                msg->c_type = MESSAGE_T__C_TYPE__CT_NONE;
I think I'm going to ask the teacher about this tomorrow, I think there's merit in _not_ discarding those values

2023-10-25 19:34 UTC, enderesting commented on source/table_skel.c
> +                msg->c_type = MESSAGE_T__C_TYPE__CT_NONE;
Plus, why else would they specify to reuse the same message otherwise? ...Shrug

2023-10-27 13:50 UTC, padrezulmiro approved these changes
We'll review this later

2023-10-27 14:05 UTC, Emily-Case approved these changes

2023-10-27 14:05 UTC, merged