Feat/client stub new
enderesting/sd-projeto-2 pull request #7
Opened 2023-10-25 20:47 UTC by Emily-Case

Only missing the two functions that free keys and entries, I am unsure of what OP_ they should send since they're not specified in the enunciado, the free keys will simply call the function in table, but free table/entries needs a new function, since we're already making one that returns the table might as well make one that frees it so we are consistent.

2023-10-26 00:14 UTC, padrezulmiro requested changes

2023-10-26 00:14 UTC, padrezulmiro commented on source/client_stub.c
> +    return res->keys;
I don't believe `res->keys` from message is null terminated like the docs require. You'll probably need to copy the whole array to a new buffer that has space for a null pointer in the end. You can use `res->nkeys` to iterate over `res->keys`

2023-10-26 00:14 UTC, padrezulmiro commented on source/client_stub.c
> +    return res->entries;
Again, `res->entries` likely isn't null terminated. Besides the return type should be an `entry_t**` but `res->entries` is a `EntryT**`.

2023-10-26 00:20 UTC, padrezulmiro commented
`rtable_free_keys` / `entries` are just utility functions that iterate over the keys/entries array and free up everything. They're not for communicating with the server side so there's no need to create a `MessageT`. It's similar to `table_free_keys` in `table.c` for example. For `rtable_free_entries` recall we have a `entry_destroy` function in `entry.c`.

2023-10-26 08:18 UTC, Emily-Case commented on source/client_stub.c
> +    return res->keys;
while I do believe the array returned from the function in table.c is NULL terminated I have implemented your suggestion.

2023-10-26 08:18 UTC, Emily-Case commented on source/client_stub.c
> +    return res->entries;
Same as above.

2023-10-26 08:19 UTC, Emily-Case commented
I have also added implementations for both free functions and I slightly changed the error checks in a couple functions based on info given by the teacher regarding OP_BAD.

2023-10-26 15:40 UTC, padrezulmiro requested changes

2023-10-26 15:40 UTC, padrezulmiro commented on source/client_stub.c
>          free(rtable_get(rtable, key));
Why is `rtable_get` needed? If your concern is that the entry doesn't exist on the server side, then there's no issue. The server should respond accordingly and send back a message with OP_ERROR. So there shouldn't be any need for either `if(!rtable_get(rtable, key)) return -1;` or this freeing.

2023-10-26 15:40 UTC, padrezulmiro commented on source/client_stub.c
> +    message_t__free_unpacked(res, NULL);
I think this will unfortunately delete all the strings in `key_arr`, since you've only copied the pointers into it. You'll have to duplicate the strings into each of `key_arr[i]` with like `strdup` for example.

2023-10-26 15:40 UTC, padrezulmiro commented on source/table_client.c
> +                rtable_free_entries(entries);
Since you've updated this, you should remove `entry_destroy`, a few lines above.

2023-10-26 15:40 UTC, padrezulmiro commented on source/table_client.c
> +                rtable_free_keys(keys);
Since you've updated this, you should remove `free(key)`, a few lines above.

2023-10-26 15:40 UTC, padrezulmiro commented on source/client_stub.c
> +    message_t__free_unpacked(res, NULL);
This has the same issue as `rtable_get_keys`.

2023-10-26 15:40 UTC, padrezulmiro commented on source/client_stub.c
> +        entry_arr[i] = res->entries[i];
This assignment won't work, since `entry_arr[i]` isn't an `EntryT` but a `entry_t`. You'll have to `malloc` space for `entry_arr[i]`, and do a deep copy of `EntryT`'s fields into the newly created entry.

2023-10-26 15:40 UTC, padrezulmiro commented on source/client_stub.c
> +    ent->value.data = entry->value->data;
I hadn't this noticed before, but it's probably better to do a deep copy into `ent->value.data`
```suggestion
    memcpy(&(ent->value.data), entry->value->data, entry->value->datasize);
```

2023-10-26 15:40 UTC, padrezulmiro commented on source/client_stub.c
> +        return -1;
I think you wanted to return `NULL` instead.

2023-10-26 18:44 UTC, Emily-Case commented on source/client_stub.c
>          free(rtable_get(rtable, key));
Agreed, I had forgotten to remove it

2023-10-26 18:44 UTC, Emily-Case commented on source/table_client.c
> +                rtable_free_entries(entries);
Fixed

2023-10-26 18:44 UTC, Emily-Case commented on source/table_client.c
> +                rtable_free_keys(keys);
Fixed

2023-10-26 18:46 UTC, Emily-Case commented on source/client_stub.c
> +        return -1;
Yes, I forgot to change the -1 there to NULL, fixed

2023-10-26 18:46 UTC, Emily-Case commented on source/client_stub.c
> +    ent->value.data = entry->value->data;
changed

2023-10-27 11:59 UTC, padrezulmiro commented on source/client_stub.c
> +    return res->keys;
I'm going to keep this conversation open in case we later find out that you were right

2023-10-27 12:00 UTC, padrezulmiro approved these changes

2023-10-27 12:00 UTC, merged